Fix trans macro
BioJulia/Libz.jl pull request #38
Opened 2016-12-11 00:24 UTC by andreasnoack

The macro behavior has been fixed in Julia master which broke the package.

2016-12-11 16:50 UTC, bicycle1885 approved these changes

2016-12-11 16:50 UTC, bicycle1885 commented
Thank you, @andreasnoack. I'd like to merge this today if no objections.

2016-12-11 20:37 UTC, yuyichao requested changes

2016-12-11 20:37 UTC, yuyichao commented on src/state.jl
> +            if $(esc(obj)).state == $(from)
Also `from` and `to`.

2016-12-11 23:15 UTC, andreasnoack commented on src/state.jl
> +            if $(esc(obj)).state == $(from)
I'll adjust but just to help my understanding, do you mind explaining why this version is not erroring?

2016-12-11 23:20 UTC, yuyichao commented on src/state.jl
> +            if $(esc(obj)).state == $(from)
They are referring to globals in the macro's module instead of locals/globals in the caller scope. These happens to be the same.

2016-12-12 01:16 UTC, andreasnoack commented on src/state.jl
> +            if $(esc(obj)).state == $(from)
Thanks. I've updated the PR.

2016-12-12 01:28 UTC, yuyichao approved these changes

2016-12-13 06:45 UTC, bicycle1885 commented
Thank you, @yuyichao. Travis CI failed on Linux (Julia 0.4) but it is not relevant to this change.

2016-12-13 06:45 UTC, merged

2016-12-20 01:44 UTC, vtjnash commented
Will there be a new METADATA release soon with this fix? (FYI, in case you haven't seen it, if you turn on [AttoBot](https://discourse.julialang.org/t/attobot-a-package-release-bot/494), making a release is as easy as making a GitHub tag 😄)

2016-12-20 02:09 UTC, bicycle1885 commented
@vtjnash Yeah, I will do soon. Give me a moment; now I'm writing a script to run a long-running program on a server 😉

2016-12-20 05:06 UTC, bicycle1885 commented
Tagged: https://github.com/JuliaLang/METADATA.jl/pull/7361